### ISSUE TITLE
seems to be broken

### ISSUE THREAD

**Issue by ar1ja** [nerdthatnoonelikes/gameoflife-py#1]
i tried running:
```
$ ./main.py --rows 6 --columns 6
```

all it did was

```
---New Gen---
  X
X  X X
 XX XX
 X XXX
 X X
 X  XX
---New Gen---
  X
X  X X
 XX XX
 X XXX
 X X
 X  XX
...
````

even after running the same command multiple times, the first generation persists.

**Comment by raghavken** [comment]
The issue happens when the board is a bit too small. Try it with a row size of 100 and a column size of 100. Hope this helps.

**Comment by ar1ja** [comment]
yep, works with larger sizes, thanks
